//
//  UIColor+Extension.swift
//  munch_3
//
//  Created by Angelina Chen on 4/30/24.
//

import Foundation
import UIKit

extension UIColor {

    // DO NOT EDIT THIS FILE

    static let a3 = A3()

    struct A3 {
        let black = UIColor.black
        let offWhite = UIColor(red: 249/255, green: 249/255, blue: 249/255, alpha: 1)
        let ruby = UIColor(red: 202/255, green: 66/255, blue: 56/255, alpha: 1)
        let silver = UIColor(red: 191/255, green: 191/255, blue: 191/255, alpha: 1)
        let white = UIColor.white
        let darkGreen = UIColor(red: 0/255, green: 100/255, blue: 0/255, alpha: 1)
        let coral = UIColor(red: 250/255, green: 50/255, blue: 10/255, alpha: 10)
        }
        
    

}
