//
//  UIColor+Extension.swift
//  munch_3
//
//  Created by Angelina Chen on 4/30/24.
//

import Foundation
import UIKit

extension UIColor {

    // DO NOT EDIT THIS FILE

    static let a3 = A3()

    struct A3 {
        let black = UIColor.black
        let offWhite = UIColor(red: 245/255, green: 245/255, blue: 245/255, alpha: 1)
        let ruby = UIColor(red: 202/255, green: 66/255, blue: 56/255, alpha: 1)
        let silver = UIColor(red: 191/255, green: 191/255, blue: 191/255, alpha: 1)
        let white = UIColor.white
        let darkGreen = UIColor(red: 0/255, green: 100/255, blue: 0/255, alpha: 1)
        let coral = UIColor(red: 243/255, green: 92/255, blue: 84/255, alpha: 1)
        let light_red = UIColor(red: 255/255, green: 100/255, blue: 50/255, alpha: 1)
        let orange = UIColor(red: 244/255, green: 149/255, blue: 45/255, alpha: 1)
        }
        
    

}
